TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += jsco4180.db
DATA += jsco4180.proto

#=======================================
include $(TOP)/configure/RULES
